import { EventEmitter } from 'eventemitter3';

export const events = {
  setQueryString: 'setQueryString',
  setQId: 'setQId',
  setQueryMode: 'setQueryMode',
  setNumberOfDocuments: 'setNumberOfDocuments',
  setRankingMode: 'setRankingMode',
  setSelectedFormats: 'setSelectedFormats',
  setCompressionLevel: 'setCompressionLevel',
  setArchiveType: 'setArchiveType',
  setUsage: 'setUsage',
  setQueryStringUrlParam: 'setQueryStringUrlParam',
  setQIdUrlParam: 'setQIdUrlParam',
  setNumberOfDocumentsUrlParam: 'setNumberOfDocumentsUrlParam',
  setRankingModeUrlParam: 'setRankingModeUrlParam',
  setExtractUrlParam: 'setExtractUrlParam',
  setCompressionLevelUrlParam: 'setCompressionLevelUrlParam',
  setArchiveTypeUrlParam: 'setArchiveTypeUrlParam',
  setUsageUrlParam: 'setUsageUrlParam',
  resetUrlParams: 'resetUrlParams',
  setQueryStringInLastRequestOfHistory: 'setQueryStringInLastRequestOfHistory',
  setNumberOfDocumentsInLastRequestOfHistory: 'setNumberOfDocumentsInLastRequestOfHistory',
  setRankingModeInLastRequestOfHistory: 'setRankingModeInLastRequestOfHistory',
  setSelectedFormatsInLastRequestOfHistory: 'setSelectedFormatsInLastRequestOfHistory',
  setCompressionLevelInLastRequestOfHistory: 'setCompressionLevelInLastRequestOfHistory',
  setArchiveTypeInLastRequestOfHistory: 'setArchiveTypeInLastRequestOfHistory',
  setUsageInLastRequestOfHistory: 'setUsageInLastRequestOfHistory',
  historyUpdated: 'historyUpdated',
  closeHistoryModal: 'closeHistoryModal',
  resultPreviewResponseReceived: 'resultPreviewResponseReceived',
  resetResultPreview: 'resetResultPreview',
  displayNotification: 'displayNotification',
  addFocusOnInput: 'addFocusOnInput',
  displayShareModal: 'displayShareModal',
  displayDownloadModal: 'displayDownloadModal',
  setNumberRowsInput: 'setNumberRowsInput',
  resetMessageImportCorpus: 'resetMessageImportCorpus',
  setQueryAdvancedSearch: 'setQueryAdvancedSearch',
};

export default new EventEmitter();
