# Intermediate image used to create the production build from the source code
FROM node:lts-alpine3.15 AS builder
LABEL stage=builder

# Copy the source code files needed to generate the production build
WORKDIR /app/
COPY ./src/ /app/src/
COPY ./public/ /app/public/
COPY ./index.html /app/index.html
COPY ./postcss.config.js /app/postcss.config.js
COPY ./tailwind.config.js /app/tailwind.config.js
COPY ./vite.config.js /app/vite.config.js
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

# Install dependancies and generate the production build
RUN npm install
RUN npm run build


# Actual image with an nginx server serving the static files generated by the builder image
FROM nginx:stable-alpine

# Copy the nginx config
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy the /app/dist/ directory of the builder image containing the production build
COPY --from=builder /app/dist/ /app/dist/

# Create the ezmaster config and make the nginx config file editable through the web interface
RUN echo '{\
  "httpPort": 80,\
  "configPath": "/etc/nginx/conf.d/default.conf",\
  "configType": "text"\
}' > /etc/ezmaster.json
