# Intermediate image used to create the production build from the source code
FROM node:lts-alpine AS builder
LABEL stage=builder

# Set the working directory
WORKDIR /app/

# Copy the npm config files and install dependencies
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json
RUN npm install

# Copy the source code files and generate the production build
COPY ./public/ /app/public/
COPY ./index.html /app/index.html
COPY ./postcss.config.js /app/postcss.config.js
COPY ./tailwind.config.js /app/tailwind.config.js
COPY ./vite.config.js /app/vite.config.js
COPY ./src/ /app/src/
RUN npm run build


# Actual image with an nginx server serving the static files generated by the builder image
FROM nginx:mainline-alpine

# Copy the nginx config
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy the /app/dist/ directory of the builder image containing the production build
COPY --from=builder /app/dist/ /app/dist/

# Create the ezmaster config and make the nginx config file editable through the web interface
RUN echo '{\
  "httpPort": 80,\
  "configPath": "/etc/nginx/conf.d/default.conf",\
  "configType": "text"\
}' > /etc/ezmaster.json
